version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'nest'
      MYSQL_PASSWORD?: 'password'
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
